#!/bin/sh
# Setup USB gadget network for Xiaomi Mi Note 3 (jason)
# Runs at sysinit phase, before NetworkManager.
# Idempotent: safe to run multiple times.

LOG_TAG="usb-gadget-setup"
USB_IP="172.16.42.1/24"
USB_ADDR="172.16.42.1"
DHCP_RANGE_START="172.16.42.2"
DHCP_RANGE_END="172.16.42.254"
DHCP_NETMASK="255.255.255.0"
DHCP_LEASE="12h"
GADGET_PATH="/sys/kernel/config/usb_gadget/g1"
DNSMASQ_CONF="/etc/dnsmasq.d/usb-gadget.conf"

log() {
    logger -t "$LOG_TAG" "$*"
    echo "$LOG_TAG: $*"
}

# 1. Mount configfs if not mounted (idempotent)
if ! mountpoint -q /sys/kernel/config 2>/dev/null; then
    log "Mounting configfs at /sys/kernel/config"
    mount -t configfs none /sys/kernel/config 2>/dev/null || \
        log "WARN: Failed to mount configfs (may already be handled by initramfs)"
else
    log "configfs already mounted"
fi

# 2. Ensure USB gadget g1 exists (initramfs should have configured it)
if [ -d "$GADGET_PATH" ]; then
    log "Gadget g1 found at $GADGET_PATH"
else
    log "Gadget g1 not found at $GADGET_PATH - assuming initramfs configures gadget, continuing with IP config"
fi

# 3. Find the USB NCM interface (usb0 or enxXX via cdc_ncm driver)
find_usb_iface() {
    # Prefer the fixed name usb0
    if ip link show usb0 >/dev/null 2>&1; then
        echo usb0
        return 0
    fi
    # Fallback: scan for cdc_ncm driver interfaces
    for dev in /sys/class/net/*; do
        [ -d "$dev" ] || continue
        name=$(basename "$dev")
        [ "$name" = "lo" ] && continue
        drvlink="$dev/device/driver"
        if [ -L "$drvlink" ]; then
            drv=$(basename "$(readlink "$drvlink")")
            if [ "$drv" = "cdc_ncm" ]; then
                echo "$name"
                return 0
            fi
        fi
    done
    return 1
}

USB_IFACE=$(find_usb_iface)
if [ -z "$USB_IFACE" ]; then
    log "ERROR: No cdc_ncm USB interface found, cannot configure IP"
    # Do not fail boot, monitor service will retry later
    exit 0
fi

log "Using USB interface: $USB_IFACE"

# 4. Configure IP on the interface (idempotent)
# 关键: 绝不 flush! 如果 add 失败 (接口在 udev rename 过渡中),
# 只 log 警告, 不清除现有 IP (initramfs 可能已配置 172.16.42.1).
# usb-ip-monitor.service 会在 multi-user 阶段重试配置.
CURRENT_IP=$(ip -4 addr show dev "$USB_IFACE" 2>/dev/null \
    | grep -oE 'inet [0-9.]+' | awk '{print $2}' || true)

if [ "$CURRENT_IP" = "$USB_ADDR" ]; then
    log "IP already $USB_ADDR on $USB_IFACE, no change"
else
    log "Configuring IP $USB_IP on $USB_IFACE (was: ${CURRENT_IP:-none})"
    ip link set "$USB_IFACE" up 2>/dev/null || \
        log "WARN: ip link set up failed for $USB_IFACE"
    # Try add; if fails, do NOT flush - initramfs IP may still be present.
    # monitor service will retry later in multi-user phase.
    ip addr add "$USB_IP" dev "$USB_IFACE" 2>/dev/null || \
        log "WARN: ip addr add failed for $USB_IFACE (monitor will retry)"
fi

# 5. Write dnsmasq DHCP server config (idempotent, rewrites each run)
mkdir -p "$(dirname "$DNSMASQ_CONF")"
cat > "$DNSMASQ_CONF" <<EOF
# DHCP server for USB gadget network (jason)
# Auto-generated by setup-usb-gadget.sh
interface=$USB_IFACE
bind-interfaces
dhcp-range=$DHCP_RANGE_START,$DHCP_RANGE_END,$DHCP_NETMASK,$DHCP_LEASE
dhcp-option=3,$USB_ADDR
dhcp-option=6,$USB_ADDR
EOF
log "Wrote dnsmasq config: $DNSMASQ_CONF (interface=$USB_IFACE)"

# 6. (Re)start dnsmasq directly (avoid systemctl which may block during early boot)
# 直接 pkill + 启动, 避免 systemctl restart 在 sysinit 阶段阻塞导致 boot 卡死
pkill -x dnsmasq 2>/dev/null || true
sleep 1
if dnsmasq --conf-file=/etc/dnsmasq.conf --conf-dir=/etc/dnsmasq.d 2>/dev/null; then
    log "dnsmasq started for $USB_IFACE"
else
    log "WARN: dnsmasq direct start failed"
fi

log "USB gadget network setup complete: $USB_IFACE -> $USB_IP"
exit 0
