#!/bin/sh
# Monitor USB NCM interface IP and reconfigure if lost.
# Runs at multi-user phase, after NetworkManager.
# Compatible with both usb0 (preferred) and enxXX (fallback) names.

LOG_TAG="usb-ip-monitor"
USB_IP="172.16.42.1/24"
USB_ADDR="172.16.42.1"
DHCP_RANGE_START="172.16.42.2"
DHCP_RANGE_END="172.16.42.254"
DHCP_NETMASK="255.255.255.0"
DHCP_LEASE="12h"
DNSMASQ_CONF="/etc/dnsmasq.d/usb-gadget.conf"
CHECK_INTERVAL=2

log() {
    logger -t "$LOG_TAG" "$*"
    echo "$LOG_TAG: $*"
}

# Find the USB NCM interface via cdc_ncm driver.
# Returns usb0 if present, else the first enxXX/cdc_ncm interface found.
find_usb_iface() {
    if ip link show usb0 >/dev/null 2>&1; then
        echo usb0
        return 0
    fi
    for dev in /sys/class/net/*; do
        [ -d "$dev" ] || continue
        name=$(basename "$dev")
        [ "$name" = "lo" ] && continue
        drvlink="$dev/device/driver"
        if [ -L "$drvlink" ]; then
            drv=$(basename "$(readlink "$drvlink")")
            if [ "$drv" = "cdc_ncm" ]; then
                echo "$name"
                return 0
            fi
        fi
    done
    return 1
}

# Update dnsmasq config to reference the active interface, then restart it.
restart_dnsmasq() {
    iface="$1"
    mkdir -p "$(dirname "$DNSMASQ_CONF")"
    cat > "$DNSMASQ_CONF" <<EOF
# DHCP server for USB gadget network (jason)
# Auto-generated by usb-ip-monitor.sh
interface=$iface
bind-interfaces
dhcp-range=$DHCP_RANGE_START,$DHCP_RANGE_END,$DHCP_NETMASK,$DHCP_LEASE
dhcp-option=3,$USB_ADDR
dhcp-option=6,$USB_ADDR
EOF
    # 直接 pkill + 启动 (避免 systemctl restart 在 monitor 循环中阻塞)
    pkill -x dnsmasq 2>/dev/null || true
    sleep 1
    dnsmasq --conf-file=/etc/dnsmasq.conf --conf-dir=/etc/dnsmasq.d 2>/dev/null || \
        log "WARN: dnsmasq direct start failed"
}

# Check and fix the USB interface IP. Returns 0 if healthy, 1 if missing.
check_and_fix_ip() {
    USB_IFACE=$(find_usb_iface)
    if [ -z "$USB_IFACE" ]; then
        log "No cdc_ncm interface found, waiting..."
        return 1
    fi

    CURRENT_IP=$(ip -4 addr show dev "$USB_IFACE" 2>/dev/null \
        | grep -oE 'inet [0-9.]+' | awk '{print $2}' || true)

    if [ "$CURRENT_IP" = "$USB_ADDR" ]; then
        # Healthy - silent to avoid log spam every 2s
        return 0
    fi

    # IP lost or wrong - reconfigure.
    # 关键: 绝不 flush! 接口可能正在被 udev/NM 重命名或重置,
    # flush 会清除任何残留 IP (包括 initramfs 配置的), 导致 USB gadget 断开.
    # 只尝试 add (如果已存在会失败, 这是 OK 的 - 下次循环重试).
    log "IP lost on $USB_IFACE (was: ${CURRENT_IP:-none}, expected: $USB_ADDR), reconfiguring (no flush)"
    ip link set "$USB_IFACE" up 2>/dev/null || true
    ip addr add "$USB_IP" dev "$USB_IFACE" 2>/dev/null || \
        log "WARN: ip addr add failed for $USB_IFACE (may already exist; will retry next cycle)"

    # Restart dnsmasq against the active interface
    restart_dnsmasq "$USB_IFACE"
    log "Reconfigured $USB_IFACE -> $USB_IP and restarted dnsmasq"
    return 0
}

log "Starting USB IP monitor (interval=${CHECK_INTERVAL}s, target=${USB_ADDR})"

while true; do
    check_and_fix_ip
    sleep "$CHECK_INTERVAL"
done
